version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: tutis_server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    env_file:
      - .env.development.local
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: smartcore.cpkphcbmk8vq.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USER: dozie
      DB_PASSWORD: smartcore29
      DB_DATABASE: smartcore

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
